import { useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api } from "../../lib/api";
import type { AlertRecord } from "../../types";

const statuses = ["GENERATED", "ACKNOWLEDGED", "ASSIGNED", "UNDER_INVESTIGATION", "RESOLVED", "CLOSED"];

export function AlertsPage() {
  const [status, setStatus] = useState("");
  const queryClient = useQueryClient();
  const alerts = useQuery({ queryKey: ["alerts", status], queryFn: () => api.get<AlertRecord[]>(`/institutional/alerts${status ? `?status=${status}` : ""}`) });
  const update = useMutation({
    mutationFn: ({ id, nextStatus }: { id: string; nextStatus: string }) => api.patch<AlertRecord>(`/institutional/alerts/${id}`, { status: nextStatus }),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["alerts"] }),
  });

  return <section className="page"><div className="page-heading"><div><span className="eyebrow">RESPONSE WORKFLOW</span><h2>Alerts</h2><p>Review and move field signals through the response lifecycle.</p></div><select className="filter-select" value={status} onChange={e => setStatus(e.target.value)}><option value="">All statuses</option>{statuses.map(item => <option key={item}>{item}</option>)}</select></div>
    {alerts.isError && <div className="notice warning"><strong>Could not load alerts.</strong><span>Verify your session and backend connection, then refresh.</span></div>}
    <div className="table-panel"><div className="table-toolbar"><span className="eyebrow">{alerts.data?.length ?? 0} RECORDS</span>{alerts.isFetching && <span className="muted-text">Refreshing...</span>}</div>{alerts.isLoading ? <div className="table-loading"><div className="spinner" /></div> : alerts.data?.length ? <div className="table-scroll"><table><thead><tr><th>Signal</th><th>Location</th><th>Crop</th><th>Severity</th><th>Status</th><th>Updated</th></tr></thead><tbody>{alerts.data.map(alert => <tr key={alert.alert_id}><td><strong>{alert.title}</strong><small>{alert.farmer_name} / {alert.plot_id.slice(0, 8)}</small></td><td>{alert.district ?? "Unspecified"}</td><td className="capitalize">{alert.crop}</td><td><span className={`severity ${alert.severity.toLowerCase()}`}>{alert.severity}</span></td><td><select className="status-select" value={alert.status} disabled={update.isPending} onChange={e => update.mutate({ id: alert.alert_id, nextStatus: e.target.value })}>{statuses.map(item => <option key={item}>{item}</option>)}</select></td><td>{new Date(alert.updated_at).toLocaleDateString()}</td></tr>)}</tbody></table></div> : <div className="empty-state"><strong>No alerts in this scope</strong><span>Signals generated by the advisory pipeline will appear here.</span></div>}</div>
  </section>;
}
