import { FormEvent, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api } from "../../lib/api";
import type { AlertRule } from "../../types";

const initial = { name: "", metric: "NDVI", operator: "<", value: "0.3", severity: "HIGH", district: "", crop: "" };

export function AlertRulesPage() {
  const [form, setForm] = useState(initial);
  const [open, setOpen] = useState(false);
  const queryClient = useQueryClient();
  const rules = useQuery({ queryKey: ["alert-rules"], queryFn: () => api.get<AlertRule[]>("/institutional/alert-rules") });
  const create = useMutation({ mutationFn: () => api.post<AlertRule>("/institutional/alert-rules", { ...form, value: Number(form.value), district: form.district || null, crop: form.crop || null, enabled: true }), onSuccess: () => { queryClient.invalidateQueries({ queryKey: ["alert-rules"] }); setForm(initial); setOpen(false); } });
  const toggle = useMutation({ mutationFn: (rule: AlertRule) => api.patch<AlertRule>(`/institutional/alert-rules/${rule.rule_id}`, { enabled: !rule.enabled }), onSuccess: () => queryClient.invalidateQueries({ queryKey: ["alert-rules"] }) });
  function submit(event: FormEvent) { event.preventDefault(); create.mutate(); }
  return <section className="page"><div className="page-heading"><div><span className="eyebrow">DETECTION CONFIGURATION</span><h2>Alert rules</h2><p>Define thresholds that turn environmental signals into reviewable alerts.</p></div><button className="primary-button compact-button" onClick={() => setOpen(value => !value)}>+ New rule</button></div>
    {open && <form className="form-panel" onSubmit={submit}><div className="panel-heading"><div><span className="eyebrow">NEW CONFIGURATION</span><h3>Alert rule</h3></div></div><div className="form-grid"><label>Name<input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} placeholder="Low NDVI warning" /></label><label>Metric<select value={form.metric} onChange={e => setForm({ ...form, metric: e.target.value })}><option>NIR</option><option>NDVI</option><option>RAINFALL</option><option>SOIL_MOISTURE</option><option>TEMPERATURE</option></select></label><label>Operator<select value={form.operator} onChange={e => setForm({ ...form, operator: e.target.value })}><option>&lt;</option><option>&gt;</option><option>DECREASE_PERCENT</option></select></label><label>Threshold<input required type="number" step="any" value={form.value} onChange={e => setForm({ ...form, value: e.target.value })} /></label><label>Severity<select value={form.severity} onChange={e => setForm({ ...form, severity: e.target.value })}><option>SAFE</option><option>MODERATE</option><option>HIGH</option><option>URGENT</option></select></label><label>District (optional)<input value={form.district} onChange={e => setForm({ ...form, district: e.target.value })} /></label><label>Crop (optional)<input value={form.crop} onChange={e => setForm({ ...form, crop: e.target.value })} /></label></div>{create.isError && <div className="form-error">Rule could not be created. Check your assigned geography.</div>}<div className="form-actions"><button type="button" className="secondary-button" onClick={() => setOpen(false)}>Cancel</button><button className="primary-button" disabled={create.isPending}>{create.isPending ? "Creating..." : "Create rule"}</button></div></form>}
    <div className="table-panel">{rules.isLoading ? <div className="table-loading"><div className="spinner" /></div> : rules.data?.length ? <div className="table-scroll"><table><thead><tr><th>Rule</th><th>Signal</th><th>Threshold</th><th>Scope</th><th>Severity</th><th>Enabled</th></tr></thead><tbody>{rules.data.map(rule => <tr key={rule.rule_id}><td><strong>{rule.name}</strong><small>Created {new Date(rule.created_at).toLocaleDateString()}</small></td><td>{rule.metric} {rule.operator}</td><td>{rule.value}</td><td>{rule.district ?? "All districts"}{rule.crop ? ` / ${rule.crop}` : ""}</td><td><span className={`severity ${rule.severity.toLowerCase()}`}>{rule.severity}</span></td><td><button className={rule.enabled ? "toggle on" : "toggle"} onClick={() => toggle.mutate(rule)} aria-label={`${rule.enabled ? "Disable" : "Enable"} ${rule.name}`}><span /></button></td></tr>)}</tbody></table></div> : <div className="empty-state"><strong>No alert rules configured</strong><span>Create a threshold to start translating signals into alerts.</span></div>}</div>
  </section>;
}
