import { FormEvent, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { api } from "../../lib/api";
import { useAuth } from "../../lib/auth";
import type { InstitutionalRole, InstitutionalUserRecord } from "../../types";

export function UserManagementPage() {
  const { user } = useAuth();
  const [open, setOpen] = useState(false);
  const [form, setForm] = useState({ email: "", password: "", role: "field_officer" as InstitutionalRole, districts: "" });
  const client = useQueryClient();
  const users = useQuery({ queryKey: ["institutional-users"], queryFn: () => api.get<InstitutionalUserRecord[]>("/institutional/users") });
  const create = useMutation({ mutationFn: () => api.post("/institutional/users", { email: form.email, password: form.password, role: form.role, assigned_geography: form.districts ? { districts: form.districts.split(",").map(value => value.trim()).filter(Boolean) } : {} }), onSuccess: () => { client.invalidateQueries({ queryKey: ["institutional-users"] }); setOpen(false); setForm({ email: "", password: "", role: "field_officer", districts: "" }); } });
  function submit(event: FormEvent) { event.preventDefault(); create.mutate(); }
  const updateRole = useMutation({
    mutationFn: ({ userId, role }: { userId: string; role: InstitutionalRole }) => api.patch(`/institutional/users/${userId}`, { role }),
    onSuccess: () => client.invalidateQueries({ queryKey: ["institutional-users"] }),
  });
  if (user?.role !== "admin") return <section className="page"><div className="notice warning"><strong>Administrator access required.</strong><span>User provisioning is restricted to institutional administrators.</span></div></section>;
  return <section className="page"><div className="page-heading"><div><span className="eyebrow">ADMINISTRATION</span><h2>Institutional users</h2><p>Provision role-based access for the operational workspace.</p></div><button className="primary-button compact-button" onClick={() => setOpen(value => !value)}>+ Add user</button></div>{open && <form className="form-panel" onSubmit={submit}><div className="form-grid"><label>Email<input required type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} /></label><label>Temporary password<input required minLength={8} type="password" value={form.password} onChange={e => setForm({ ...form, password: e.target.value })} /></label><label>Role<select value={form.role} onChange={e => setForm({ ...form, role: e.target.value as InstitutionalRole })}><option value="field_officer">Field officer</option><option value="district_officer">District officer</option><option value="analyst">Analyst</option><option value="admin">Admin</option></select></label></div><label>Assigned districts<input value={form.districts} onChange={e => setForm({ ...form, districts: e.target.value })} placeholder="Comma-separated, optional" /></label>{create.isError && <div className="form-error">User could not be created. This action requires administrator access.</div>}<div className="form-actions"><button type="button" className="secondary-button" onClick={() => setOpen(false)}>Cancel</button><button className="primary-button" disabled={create.isPending}>{create.isPending ? "Creating..." : "Create user"}</button></div></form>}<div className="table-panel">{users.isLoading ? <div className="table-loading"><div className="spinner" /></div> : users.data?.length ? <div className="table-scroll"><table><thead><tr><th>User</th><th>Role</th><th>Geography</th><th>Created</th><th>Last login</th></tr></thead><tbody>{users.data.map(row => <tr key={row.user_id}><td><strong>{row.email}</strong><small>{row.user_id.slice(0, 8)}</small></td><td><select value={row.role} disabled={updateRole.isPending} onChange={e => updateRole.mutate({ userId: row.user_id, role: e.target.value as InstitutionalRole })}><option value="field_officer">Field officer</option><option value="district_officer">District officer</option><option value="analyst">Analyst</option><option value="admin">Admin</option></select></td><td>{row.assigned_geography.districts?.join(", ") || "All assigned scope"}</td><td>{new Date(row.created_at).toLocaleDateString()}</td><td>{row.last_login_at ? new Date(row.last_login_at).toLocaleDateString() : "Never"}</td></tr>)}</tbody></table></div> : <div className="empty-state"><strong>No users found</strong><span>Provision the first institutional user.</span></div>}{updateRole.isError && <div className="notice warning"><strong>Role update failed.</strong><span>Only administrators can change another user's role.</span></div>}</div></section>;
}
