import { useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { api } from "../../lib/api";
import type { IngestionLatest, Prediction, PredictionExplanation } from "../../types";

export function IntelligencePage() {
  const [plotId, setPlotId] = useState("");
  const [loaded, setLoaded] = useState(false);
  const liveQueryOptions = { refetchInterval: loaded ? 30_000 : false, refetchOnWindowFocus: loaded } as const;
  const prediction = useQuery({ queryKey: ["prediction", plotId], queryFn: () => api.get<Prediction>(`/predictions/latest/${plotId}`), enabled: loaded, ...liveQueryOptions });
  const satellite = useQuery({ queryKey: ["satellite", plotId], queryFn: () => api.get<IngestionLatest>(`/ingest/latest/${plotId}`), enabled: loaded, ...liveQueryOptions });
  const ingest = useMutation({ mutationFn: () => api.post<{ records_ingested: number; data_types: string[] }>(`/ingest/${plotId}`), onSuccess: () => { void satellite.refetch(); void prediction.refetch(); } });
  const advisory = useMutation({ mutationFn: () => api.post<Prediction & { message: string; sms_status: string }>(`/advisories/generate/${plotId}`), onSuccess: () => { void prediction.refetch(); void explanation.refetch(); } });
  const explanation = useQuery({ queryKey: ["prediction-explanation", prediction.data?.prediction_id], queryFn: () => api.get<PredictionExplanation>(`/predictions/explain/${prediction.data?.prediction_id}`), enabled: Boolean(prediction.data?.prediction_id) });
  function load() { if (!plotId.trim()) return; setLoaded(true); void prediction.refetch(); void satellite.refetch(); }
  return <section className="page"><div className="page-heading"><div><span className="eyebrow">ML + SATELLITE INTELLIGENCE</span><h2>Plot intelligence</h2><p>Inspect the latest signal, model output, and advisory action for a plot.</p></div></div><div className="lookup-bar"><label>Plot ID<input value={plotId} onChange={e => setPlotId(e.target.value)} placeholder="Enter an authorized plot ID" /></label><button className="primary-button" onClick={load} disabled={!plotId.trim()}>Load plot</button></div>
    {(prediction.isError || satellite.isError) && <div className="notice warning"><strong>Plot data could not be loaded.</strong><span>Confirm the plot ID is inside your assigned geography.</span></div>}
    <div className="content-grid intelligence-grid"><div className="panel"><div className="panel-heading"><div><span className="eyebrow">LATEST MODEL OUTPUT</span><h3>Irrigation stress</h3></div>{prediction.data && <span className={`severity ${(prediction.data.urgency ?? "safe").toLowerCase()}`}>{prediction.data.urgency ?? prediction.data.predicted_class}</span>}</div>{prediction.isFetching ? <div className="table-loading"><div className="spinner" /></div> : prediction.data ? <><div className="prediction-result"><strong>{prediction.data.predicted_class.replace(/_/g, " ")}</strong><span>{prediction.data.reason ?? prediction.data.advice ?? "No explanation supplied."}</span></div><div className="detail-stats"><div><span>SOIL MOISTURE</span><strong>{prediction.data.soil_moisture_pct?.toFixed(1) ?? "--"}%</strong></div><div><span>CONFIDENCE</span><strong>{prediction.data.confidence != null ? `${(prediction.data.confidence * 100).toFixed(0)}%` : "--"}</strong></div></div><div className="action-row"><button className="primary-button" onClick={() => advisory.mutate()} disabled={advisory.isPending}>{advisory.isPending ? "Generating..." : "Generate advisory"}</button>{prediction.data.fallback_used && <span className="fallback-note">Fallback model used</span>}</div>{advisory.data && <div className="notice"><strong>Advisory {advisory.data.sms_status}</strong><span>{advisory.data.message}</span></div>}</> : <div className="empty-state compact"><strong>Enter a plot ID</strong><span>Latest prediction and explainability data will appear here.</span></div>}</div>
      <div className="panel"><div className="panel-heading"><div><span className="eyebrow">LATEST OBSERVATIONS</span><h3>Satellite inputs</h3></div><button className="secondary-button" disabled={!plotId || ingest.isPending} onClick={() => ingest.mutate()}>{ingest.isPending ? "Ingesting..." : "Trigger ingestion"}</button></div>{satellite.data ? <div className="observation-list"><Observation label="NDVI" value={satellite.data.ndvi[0]?.value} date={satellite.data.ndvi[0]?.date} /><Observation label="SAR" value={satellite.data.sar[0]?.value} date={satellite.data.sar[0]?.date} /><Observation label="Weather" value={satellite.data.weather[0]?.value} date={satellite.data.weather[0]?.date} /></div> : <div className="empty-state compact"><strong>No observation loaded</strong><span>Load a plot to inspect the latest provider data.</span></div>}{ingest.data && <div className="notice"><strong>Ingestion accepted</strong><span>{ingest.data.records_ingested} records written: {ingest.data.data_types.join(", ")}</span></div>}{explanation.data && <div className="explanation-block"><span className="eyebrow">FEATURE IMPACTS</span>{Object.entries(explanation.data.feature_impacts).map(([name, impact]) => <div className="impact-row" key={name}><span>{name.replace(/_/g, " ")}</span><strong className={impact.direction}>{impact.impact > 0 ? "+" : ""}{impact.impact.toFixed(2)}</strong><small>{impact.note}</small></div>)}</div>}</div></div>
  </section>;
}
function Observation({ label, value, date }: { label: string; value?: string; date?: string }) { return <div className="observation-row"><span>{label}</span><strong>{value ?? "--"}</strong><small>{date ?? "No date"}</small></div>; }
