import { useMutation, useQuery } from "@tanstack/react-query";
import { useFarmerAuth } from "../../lib/farmerAuth";
import { api, farmerPath } from "../../lib/api";
import type { FarmerAdvisory, FarmerPlot, Prediction } from "../../types";

export function FarmerDashboardPage() {
  const { farmer, session, logout } = useFarmerAuth();
  const plots = useQuery({ queryKey: ["farmer-plots", session?.farmer_id], queryFn: () => api.get<FarmerPlot[]>(farmerPath(`/plots/${session!.farmer_id}`, session!.session_token)), enabled: Boolean(session) });
  const predictions = useQuery({ queryKey: ["farmer-predictions", plots.data?.map(plot => plot.plot_id)], queryFn: async () => Promise.all((plots.data ?? []).map(async plot => ({ plot, prediction: await api.get<Prediction>(`/predictions/latest/${plot.plot_id}`).catch(() => null) }))), enabled: Boolean(plots.data) });
  const advisory = useMutation({ mutationFn: (plotId: string) => api.post<FarmerAdvisory & { message: string; sms_status: string }>(`/advisories/generate/${plotId}`) });
  if (!session) return null;
  return <div className="farmer-shell"><header className="farmer-topbar"><div className="brand"><span className="brand-mark">K</span><div><strong>KrishiMitra</strong><small>Farmer advisory</small></div></div><div className="farmer-user"><span>{farmer?.name ?? farmer?.phone_number ?? "Farmer"}</span><button className="secondary-button" onClick={logout}>Sign out</button></div></header><main className="farmer-main"><div className="page-heading"><div><span className="eyebrow">FARMER DASHBOARD</span><h2>Your farm signals</h2><p>Latest crop status and practical guidance for your registered plots.</p></div></div>{plots.isError && <div className="notice warning"><strong>Plots could not be loaded.</strong><span>Please try again when you have a connection.</span></div>}{plots.isLoading ? <div className="table-loading"><div className="spinner" /></div> : plots.data?.length ? <div className="farmer-plot-grid">{plots.data.map(plot => { const result = predictions.data?.find(item => item.plot.plot_id === plot.plot_id)?.prediction; return <article className="farmer-plot-card" key={plot.plot_id}><div className="panel-heading"><div><span className="eyebrow">PLOT</span><h3>{plot.plot_nickname ?? plot.crop_type}</h3></div><span className="severity safe">{plot.status}</span></div><p className="capitalize">{plot.crop_type} · {plot.village_name ?? "Location not shared"}</p>{result ? <div className="farmer-signal"><span className="eyebrow">LATEST ADVICE</span><strong>{result.predicted_class.replace(/_/g, " ")}</strong><span>{result.advice ?? result.reason ?? "Keep monitoring your crop."}</span><small>Confidence: {result.confidence != null ? `${Math.round(result.confidence * 100)}%` : "not available"}</small></div> : <div className="empty-state compact"><span>No recent signal yet.</span></div>}<button className="primary-button" onClick={() => advisory.mutate(plot.plot_id)} disabled={advisory.isPending}>{advisory.isPending ? "Preparing..." : "Get advisory"}</button>{advisory.data?.plot_id === plot.plot_id && <div className="notice"><strong>Advisory ready</strong><span>{advisory.data.message}</span></div>}</article>; })}</div> : <div className="empty-state"><strong>No plots registered</strong><span>Your field officer can add a plot after registration.</span></div>}</main></div>;
}
